# Generated by Django 4.0.2 on 2022-02-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='linkoke',
        ),
    ]
