# Generated by Django 4.0.2 on 2022-02-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='UserName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
