# Generated by Django 4.0.2 on 2022-02-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_transaction_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quatily',
            field=models.IntegerField(null=True, unique=0),
        ),
    ]
