# Generated by Django 4.0.2 on 2022-02-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_buy_quantily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='quantily',
            field=models.IntegerField(),
        ),
    ]
