# Generated by Django 4.0.2 on 2022-03-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_users_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='ProductType',
        ),
    ]
