# Generated by Django 4.0.2 on 2022-03-09 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_product_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.producttype'),
        ),
    ]
